services:
  camera_node:
    image: droneblocks/dexi-pi-camera-ros
    container_name: camera_node
    command: ros2 run camera_ros camera_node --ros-args -p width:=320 -p height:=240
    privileged: true
    volumes:
      - /dev:/dev/
      - /run/udev:/run/udev/
    group_add:
      - video

  object_detection_node:
    image: droneblocks/dexi-tensorflow-ros
    container_name: object_detection_node
    command: ros2 run ros2_tensorflow_picam object_detection_node

  web_video_server_node:
    image: droneblocks/dexi-web-video-server-ros
    container_name: web_video_server
    ports:
      - "8080:8080"